<style>
.leadimg{
    width: 30px;
    height: 30px;

}
</style>
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);"><?=CS_COMPANY?></a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </div>
                <h4 class="page-title">All Leads</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <a href="?module=leads&action=index" type="button" class="btn btn-sm btn-blue waves-effect waves-light float-right">
                    <i class="mdi mdi-plus-circle"></i> New Lead
                </a>
                <h4 class="header-title mb-4">Manage Leads</h4>

                <table class="table table-hover m-0 table-centered dt-responsive nowrap w-100" id="datatable-buttons">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <!-- <th>Car Image</th> -->
                            <!-- <th>Car Name</th> -->
                            <th>Client Name</th>
                            <th>Generated By</th>
                            <!-- <th>Status</th> -->
                            <th>Created Date</th>
                            <th class="hidden-sm">Action</th>
                        </tr>
                    </thead>

                    <tbody>


                        <? if (count($allleads)) {
                          $count = 1;
                          foreach ($allleads as $id => $R) { ?>



                            <tr>
                                <td><b><?= $count ?></b></td>
                                <!-- <td>
                                    <a href="<?= $R['link'] ?>" target="_blank" class="text-body">
                                        <img src="assets/images/products/<?= $R['image'] ?>" alt="contact-img" title="contact-img" class="rounded-square avatar-sm" />
                                    </a>
                                </td> -->
                                <!-- <td> <?= $R['brandName'] ?> <?= $R['makeName'] ?> <?= $R['year'] ?> </td> -->
                                <td><?= $R['clientname'] ?></td>
                                <td><?= $R['createdBy'] ?></td>
                                <!-- <td><span class="badge badge-success"><?= $R['status'] ?></span></td> -->
                                <td><?= $R['doc'] ?></td>
                                <td>
                                    <div class="btn-group dropdown">
                                        <a href="javascript: void(0);" class="table-action-btn dropdown-toggle arrow-none btn btn-light btn-sm" data-toggle="dropdown" aria-expanded="false"><i class="mdi mdi-dots-horizontal"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" data-id="<?= $R['id']?>" onclick="getleaddetails(this);" data-toggle="modal" data-target="#bs-example-modal-lg"><i class="mdi mdi-magnify-plus-outline mr-2 font-18 text-muted vertical-middle"></i>View Lead</a>
                                            <!-- <a class="dropdown-item" href="#"><i class="mdi mdi-check-all mr-2 text-muted font-18 vertical-middle"></i>Generate Order</a> -->
                                            <a class="dropdown-item" href="?module=leads&action=index&id=<?= $R['id']?>"><i class="mdi mdi-pencil mr-2 text-muted font-18 vertical-middle"></i>Edit Lead</a>
                                            <a class="dropdown-item text-danger" href="?module=leads&action=delete&id=<?= $R['id']?>"><i class="mdi mdi-delete mr-2 text-danger font-18 vertical-middle"></i>Remove</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        <?php $count++;
                                        }
                                    } else { ?>
                        <tr>
                            <td class="text-center not-found" colspan="9">No Records Found</td>
                        </tr>
                        <? } ?>



                    </tbody>
                </table>
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->
    <!-- end row -->
        


    <!--  Modal content for the Large example -->
    <div class="modal fade" id="bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myLargeModalLabel">Single Order</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                <form class="form" action="?module=grn_interco&action=process" method="post">

                    <table class="table table-sm mb-0">
                        <thead>
                            <tr>
                                <!-- <th> <span class="fa fa-check"></span> </th> -->
                                <th>Car Image</th>
                                <th>Car Name</th>
                                <th>Amount</th>
                                <th>leadStatus</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                            <tbody id="droparea">

                                <!-- <tr>
                                    <td> <input class='custom-control' type='checkbox' name='' value=''> </td>
                                    <td>Product Name</td>
                                    <td>25</td>
                                    <td><span class='fa fa-check'></span></td>
                                </tr> -->

                            </tbody>
                    </table>
                    _______________________________________________<br><br>
                    <button class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
                </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->



</div> <!-- container -->


<script>
    function getleaddetails(obj) {
        var leadid = $(obj).attr("data-id");
        // console.log(leadid);


        $.get("?module=leads&action=getleaddetails&format=json&leadid="+leadid,null,function(data){
            var leaddetails = eval(data);
            // console.log(eval(leaddetails));
            $("#droparea").empty();
            $.each(leaddetails[0].details,function(index,value){
                // console.log(value.detailProcessed);
                if (value.statusid == 3 || value.statusid == 4 ) {
                    var action = "";
                    var icon = "circle";
                }else {
                    // var action = "<span class='fa fa-check text-success'></span>";
                    // var action = "<span data-leadid='"+leadid+"' data-detailsid='"+value.id+"' onclick='generateorder(this);' class='fa fa-check text-success'></span> &nbsp;<span class='far fa-window-close text-danger'></span>";
                    var action = "<span data-leadid='"+leadid+"' data-detailsid='"+value.id+"' onclick='generateorder(this);' class='fa fa-check text-success'></span> &nbsp;<span data-leadid='"+leadid+"' data-detailsid='"+value.id+"' onclick='closeorder(this);'  class='far fa-window-close text-danger'></span>";
                    // var icon = "check";
                }
                var leaddata = "<tr class='leaddetails fadee' for='check"+index+"'><td> <img class='avatar-md rounded-circle leadimg' src='assets/images/products/"+value.image+"' </td> <td>"+value.brandName+" "+value.makeName+" "+value.year+"</td> <td class='numberWithCommas'>"+value.amount+" Tzs</td> <td>"+value.leadStatus+"</td> <td>"+action+"</td> </tr>";
                // console.log(leaddata);
                    setTimeout(function(){
                    $("#droparea").append(leaddata);
                },200 * index);

            })

        })

    }

    function generateorder(obj) {
        var leadid = $(obj).attr("data-leadid");
        var detailsid = $(obj).attr("data-detailsid");
        
        // console.log(leadid);
        // similar behavior as clicking on a link
        window.location.href = "?module=orders&action=add&leadid="+leadid+"&detailsid="+detailsid+"";
    }

    function closeorder(obj) {
        var leadid = $(obj).attr("data-leadid");
        var detailsid = $(obj).attr("data-detailsid");
        console.log(detailsid);
        console.log(leadid);
        
        window.location.href = "?module=leads&action=marklost&leadid="+leadid+"&id="+detailsid+"";
    }



    function numberWithCommas(number) {
        var parts = number.toString().split(".");
        parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
        return parts.join(".");
    }

    $(document).ready(function() {
        $(".numberWithCommas").each(function() {
            var num = $(this).text();
            var commaNum = numberWithCommas(num);
            $(this).text(commaNum);
        });
    });
</script>
